### ISSUE TITLE
Does not remember cursor position

### ISSUE THREAD

**Issue by laurence-do** [dy-sh/obsidian-remember-cursor-position#25]
This plugin has been working amazingly until about a week ago.  Now it does not seem to record the current position anymore?  I tried even on a blank vault with no other plugins installed.  I see cursor-positions.json is being updated, but all the positions are 0

{"Doc A.md":{"scroll":null},"Doc B.md":{"scroll":0,"cursor":{"from":{"ch":0,"line":0},"to":{"ch":0,"line":0}}}}

**Comment by laurence-do** [comment]
Weird... I'm seeing that when switching notes, getEphemeralState() returns { scroll: NaN }.  I updated checkEphemeralStateChanged() to skip saving the state if scrolls is NaN, and it seems to work now.

Maybe this will help someone else 🤷‍♂️  Change
`
        if (!this.isEphemeralStatesEquals(st, this.lastEphemeralState)) {
            this.saveEphemeralState(st);
            this.lastEphemeralState = st;
        }
`
to: 
`
        if (!isNaN(st.scroll) && !this.isEphemeralStatesEquals(st, this.lastEphemeralState)) {
            this.saveEphemeralState(st);
            this.lastEphemeralState = st;
        }
`

**Comment by dy-sh** [comment]
Thank you! Will check it.

**Comment by chrisynl** [comment]
> Weird... I'm seeing that when switching notes, getEphemeralState() returns { scroll: NaN }. I updated checkEphemeralStateChanged() to skip saving the state if scrolls is NaN, and it seems to work now.
> 
> Maybe this will help someone else man_shrugging
> 
> Change
> 
> if (!this.isEphemeralStatesEquals(st, this.lastEphemeralState)) { this.saveEphemeralState(st); this.lastEphemeralState = st; }
> 
> to:
> 
> if (!isNaN(st.scroll) && !this.isEphemeralStatesEquals(st, this.lastEphemeralState)) { this.saveEphemeralState(st); this.lastEphemeralState = st; }

Thank you! It works for me.

**Comment by joezhouchenye** [comment]
> Weird... I'm seeing that when switching notes, getEphemeralState() returns { scroll: NaN }. I updated checkEphemeralStateChanged() to skip saving the state if scrolls is NaN, and it seems to work now.
> 
> Maybe this will help someone else 🤷‍♂️
> 
> Change
> 
> if (!this.isEphemeralStatesEquals(st, this.lastEphemeralState)) { this.saveEphemeralState(st); this.lastEphemeralState = st; }
> 
> to:
> 
> if (!isNaN(st.scroll) && !this.isEphemeralStatesEquals(st, this.lastEphemeralState)) { this.saveEphemeralState(st); this.lastEphemeralState = st; }

Thank you! It works!

**Comment by giloliveira-nmi** [comment]
> Weird... I'm seeing that when switching notes, getEphemeralState() returns { scroll: NaN }. I updated checkEphemeralStateChanged() to skip saving the state if scrolls is NaN, and it seems to work now.
> 
> Maybe this will help someone else 🤷‍♂️
> 
> Change
> 
> if (!this.isEphemeralStatesEquals(st, this.lastEphemeralState)) { this.saveEphemeralState(st); this.lastEphemeralState = st; }
> 
> to:
> 
> if (!isNaN(st.scroll) && !this.isEphemeralStatesEquals(st, this.lastEphemeralState)) { this.saveEphemeralState(st); this.lastEphemeralState = st; }

Stopped working for me as well after the recent update for Obsidian. This works!

**Comment by dy-sh** [comment]
Plugin updated. Thank you!
