### ISSUE TITLE
Twitching behaviour since last update

### ISSUE THREAD

**Issue by zanodor** [dy-sh/obsidian-remember-cursor-position#47]
I was going to make a gif on this happening but when I prepared my ShareX program last time around, I was not able to reproduce.  

The twitching between two cursor positions lasts for 6-10 jumps then ceases.  
- Comment: this is not the same lag behaviour as it happens in a very long note.  

[Linux, Windows]

**Comment by rasmusrhl** [comment]
- I think I have the same problem.
- The when I press Ctrl + tab to open the note in the next tab, the display 'jump's up and down for 3 seconds. 
- This problem disappears when I disable 'remember cursor position'.

Thank you for this plugin. It worked perfectly until recently 😊

**Comment by niecailong** [comment]
I also take this problem，hope you to fix. Thank you for this plugin。
